"""Network operations."""
import os
import re
import tempfile
import ipaddress
import psutil
from typing import Dict, List
from utils.helpers import run_cmd, safe_quote


def _validate_dns_server(s: str) -> bool:
    """Validate IPv4 or IPv6 address."""
    try:
        ipaddress.ip_address(s)
        return True
    except ValueError:
        return False


def get_network_interfaces() -> List[Dict]:
    interfaces: List[Dict] = []
    addrs = psutil.net_if_addrs()
    stats = psutil.net_if_stats()
    for name, addr_list in addrs.items():
        info: Dict = {"name": name, "ipv4": [], "ipv6": [], "mac": ""}
        for addr in addr_list:
            if addr.family.name == "AF_INET": info["ipv4"].append(addr.address)
            elif addr.family.name == "AF_INET6": info["ipv6"].append(addr.address)
            elif addr.family.name == "AF_PACKET": info["mac"] = addr.address
        if name in stats: info["is_up"] = stats[name].isup; info["speed"] = stats[name].speed
        interfaces.append(info)
    return interfaces


def get_dns() -> List[str]:
    dns: List[str] = []
    try:
        with open("/etc/resolv.conf") as f:
            for line in f:
                if line.strip().startswith("nameserver"): dns.append(line.strip().split()[1])
    except Exception: pass
    return dns


def set_dns(servers: List[str]) -> Dict:
    """Update DNS servers in /etc/resolv.conf."""
    if not servers:
        return {"success": False, "message": "At least one DNS server is required"}
    for s in servers:
        if not _validate_dns_server(s):
            return {"success": False, "message": f"Invalid DNS server: {s}"}
    content = "# Generated by Linux Toolbox\n"
    for s in servers:
        content += f"nameserver {s}\n"
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".resolv", delete=False)
    try:
        tmp.write(content)
        tmp.close()
        _, code = run_cmd(f"sudo cp {safe_quote(tmp.name)} /etc/resolv.conf")
        return {"success": code == 0, "message": "DNS updated" if code == 0 else "Failed to update DNS"}
    finally:
        try: os.remove(tmp.name)
        except OSError: pass


def get_firewall_status() -> Dict:
    for fw, cmds in [("UFW", ["which ufw", "sudo ufw status 2>/dev/null"]), ("Firewalld", ["which firewall-cmd", "sudo firewall-cmd --state 2>/dev/null"]), ("nftables", ["which nft", "sudo nft list ruleset 2>/dev/null | head -5"]), ("iptables", ["which iptables", "sudo iptables -L -n 2>/dev/null | head -5"])]:
        _, code = run_cmd(cmds[0])
        if code == 0:
            status, _ = run_cmd(cmds[1])
            return {"name": fw, "status": status or "configured"}
    return {"name": "Unknown", "status": "not detected"}


def get_listen_ports() -> List[Dict]:
    """Get list of listening ports."""
    ports = []
    out, _ = run_cmd("ss -tlnp 2>/dev/null")
    for line in out.splitlines()[1:]:  # skip header
        parts = line.split()
        if len(parts) >= 5:
            local = parts[3] if len(parts) > 3 else ""
            process = parts[-1] if "users:" in parts[-1] else ""
            # Extract process name from users:(("name",pid=,fd=))
            m = re.search(r'\(\("([^"]+)"', process)
            proc_name = m.group(1) if m else ""
            ports.append({"protocol": "tcp", "local_address": local, "process": proc_name})
    # Also get UDP
    out, _ = run_cmd("ss -ulnp 2>/dev/null")
    for line in out.splitlines()[1:]:
        parts = line.split()
        if len(parts) >= 5:
            local = parts[3] if len(parts) > 3 else ""
            process = parts[-1] if "users:" in parts[-1] else ""
            m = re.search(r'\(\("([^"]+)"', process)
            proc_name = m.group(1) if m else ""
            ports.append({"protocol": "udp", "local_address": local, "process": proc_name})
    return ports
