"""System operations package.

Re-exports all public functions and constants from submodules so
``from core.system import get_system_info`` continues to work.
"""
from .sysctl import (
    _get_uptime,
    get_system_info,
    get_timezone_list,
    get_locale_list,
    set_hostname,
    set_timezone,
    set_locale,
    get_sysctl_params,
    set_sysctl_param,
    persist_sysctl,
    get_hosts,
    save_hosts,
    get_ssh_config,
    save_ssh_config,
    get_swap_info,
    create_swap,
    disable_swap,
    check_available_features,
    generate_diagnostic_report,
    get_thermal,
    get_notifications,
    get_cpu_freq_details,
)
from .users import (
    get_users,
    add_user,
    delete_user,
    change_password,
)
from .logs import (
    get_journal_logs,
    get_dmesg,
    get_audit_logs,
    get_crontab,
    set_crontab,
    get_ntp_status,
    toggle_ntp,
    get_ulimits,
    save_ulimits,
    get_kernel_modules,
    manage_kernel_module,
)
from .boot import (
    get_grub_config,
    set_grub_default,
    set_grub_cmdline,
    get_cpu_governor,
    set_cpu_governor,
    get_io_scheduler,
    set_io_scheduler,
    repair_grub,
    rebuild_initramfs,
    get_mac_status,
    set_selinux_mode,
)
from .timers import (
    list_systemd_timers,
    get_timer_detail,
    timer_action,
    parse_crontab,
    get_system_crontabs,
)
from .processes import (
    list_processes,
    get_process_tree,
    get_process_detail,
    kill_process,
    renice_process,
    get_system_load,
    get_top_processes,
)
from .profiles import (
    COMMON_UNNECESSARY_SERVICES,
    QUICK_KERNEL_PARAMS,
    OPTIMIZATION_PROFILES,
    BOOT_PARAM_PRESETS,
    get_service_optimization,
    optimize_services,
    get_quick_kernel_params,
    apply_quick_kernel_params,
    get_optimization_preview,
    apply_optimization_profile,
    save_kernel_profile,
    list_kernel_profiles,
    load_kernel_profile,
    apply_kernel_profile,
    delete_kernel_profile,
    compare_kernel_profile,
)

__all__ = [
    # sysctl
    "get_system_info",
    "get_timezone_list",
    "get_locale_list",
    "set_hostname",
    "set_timezone",
    "set_locale",
    "get_sysctl_params",
    "set_sysctl_param",
    "persist_sysctl",
    "get_hosts",
    "save_hosts",
    "get_ssh_config",
    "save_ssh_config",
    "get_swap_info",
    "create_swap",
    "disable_swap",
    "check_available_features",
    "generate_diagnostic_report",
    "get_thermal",
    "get_notifications",
    "get_cpu_freq_details",
    # users
    "get_users",
    "add_user",
    "delete_user",
    "change_password",
    # logs
    "get_journal_logs",
    "get_dmesg",
    "get_audit_logs",
    "get_crontab",
    "set_crontab",
    "get_ntp_status",
    "toggle_ntp",
    "get_ulimits",
    "save_ulimits",
    "get_kernel_modules",
    "manage_kernel_module",
    # boot
    "get_grub_config",
    "set_grub_default",
    "set_grub_cmdline",
    "get_cpu_governor",
    "set_cpu_governor",
    "get_io_scheduler",
    "set_io_scheduler",
    "repair_grub",
    "rebuild_initramfs",
    "get_mac_status",
    "set_selinux_mode",
    # profiles
    "COMMON_UNNECESSARY_SERVICES",
    "QUICK_KERNEL_PARAMS",
    "OPTIMIZATION_PROFILES",
    "BOOT_PARAM_PRESETS",
    "get_service_optimization",
    "optimize_services",
    "get_quick_kernel_params",
    "apply_quick_kernel_params",
    "get_optimization_preview",
    "apply_optimization_profile",
]
